FROM agrigorev/zoomcamp-model:2025

WORKDIR /code

# Copy the Q6 FastAPI script
COPY main_q6.py main.py

# Install dependencies if needed
RUN pip install --no-cache-dir fastapi uvicorn scikit-learn 

EXPOSE 9696

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9696"]