FROM agrigorev/model-2025-hairstyle:v1

RUN pip install pillow onnxruntime

COPY lambda_function.py .
CMD ["python", "-c", "from lambda_function import lambda_handler; "
                    "print(lambda_handler({'url': 'https://habrastorage.org/webt/yf/_d/ok/yf_dokzqy3vcritme8ggnzqlvwa.jpeg'}))"]
