FROM agrigorev/zoomcamp-model:2025

# Set working directory
WORKDIR /app

# Copy your dependency file
COPY pyproject.toml .

# Install uv and dependencies
RUN pip install uv
RUN uv pip install --system --no-cache fastapi uvicorn scikit-learn pydantic

# Copy your FastAPI script and model
COPY main.py .

# Expose port
EXPOSE 9696

# Run the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "9696"]
